#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_side.xyz"
EWW="$HOME/.local/bin/eww/eww -c $HOME/.config/eww/leftbar"

## window list
w_ls="
    main \
    pfp \
    seper \
    song \
    sys_usg \
    song_prog \
    dir \
    song_ctl \
    audio \
    quote \
    sys_tray \
    time
"
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

run_eww() {
    ${EWW} open-many $w_ls
}


if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww 
else
    ${EWW} close $w_ls 
	rm "$FILE"
fi
