#!/bin/sh

calendar() {
LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="$HOME/.local/bin/eww/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
}

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run && echo "ok good!"
else
    ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
    rm "$LOCK_FILE" && echo "closed"
fi
}

if [ "$1" = "calendar" ]; then
calendar
fi
