#!/bin/bash

    cmd="$(amixer -D pulse sget Master | grep 'Front Left:' | awk '{ print $6 }')"


    if [ "$cmd" = "[on]" ]; then
        col="#0f0f17"
        bg="#bbc5d7"
        icon=""
    else
        bg="transparent"
        col="#0f0f17"
        icon=""
    fi



if [ $1 = "vol" ]; then
    echo $icon
elif [ $1 = "vol_col" ]; then
    echo $col
elif [ $1 = "vol_bg" ]; then
    echo $bg
fi
