require("signal.battery")
require("signal.bright")
-- require("signal.volume")
require("signal.wifi")
require("signal.bluetooth")
require("signal.ram")
require("signal.cpu")
require("signal.vol")
require("mods.window_switcher").enable()
